version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:13.14.0
    working_directory: ~/app

jobs:
  check_branch_name:
    docker:
      - image: circleci/node:13.14.0
    working_directory: ~/app
    steps:
      - run:
          name: fail if the branch name does not start with a valid prefix
          command: |
            branch=$CIRCLE_BRANCH
            if [[ "$branch" =~ ^(fix|feature|breaking)/ || "$branch" == 'master' ]]
            then
              echo $branch is a valid name
            else
              echo $branch is not valid because the branch name must match '^(fix|feature|breaking)/' or be master
              exit 1
            fi
  test:
    executor: node-executor
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn lint
      - run: yarn test --coverage
      - run:
          name: Generate coveralls config
          command: "echo repo_token: $COVERALLS_REPO_TOKEN > ./.coveralls.yml"
      - persist_to_workspace:
          root: ~/app
          paths:
            - .git
            - node_modules
            - .coveralls.yml
            - coverage
  publish_package:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/app
      - run: cat ./coverage/lcov.info
      - run: git checkout .
      - run:
          name: Upload coverage to coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - check_branch_name
      - test:
          requires:
            - check_branch_name
      - publish_package:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - fix/inspect-ci
